connect 'admindoc' user sysdba password 'masterkey';

create table devices (
	id_device int generated by default as identity primary key,
	alias varchar(64),
	ipv4 varchar(64),
	ipv6 varchar(64),
	fqdn varchar(64)
);
commit;

create table users (
	id_user int generated by default as identity primary key,
	email varchar(64),
	password_hash varchar(64),
	first_name varchar(64),
	last_name varchar(64)
);
commit;

create table external_users (
	id_user_external int generated by default as identity primary key,
	id_user int references users,
	email varchar(64),
	password_hash varchar(64)
);
commit;

create table user_devices (
	id_user_devices int generated by default as identity primary key,
	id_user int references users,
	id_device int references devices
);
commit;

create table roles (
	id_role int generated by default as identity primary key,
	alias varchar(64),
	role_content varchar(128)
);
commit;

create table user_permissions (
	id_permission int generated by default as identity primary key,
	id_user int references users,
	id_role int references roles
);
commit;

create table services (
	id_service int generated by default as identity primary key,
	alias varchar(64),
	fqdn varchar(64)
);
commit;

create table user_services (
	id_user_services int generated by default as identity primary key,
	id_user int references users,
	id_service int references services
);
commit;
